name: "Nix Flake CI"

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: Nix Flake Build & Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v14
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v7

    - name: Build the default flake output
      run: nix build

    - name: Check the flake outputs
      run: nix flake check

    - name: Check the license headers
      run: nix develop --command licensure --project --check

    - name: Check the flake's formatting
      run: nix develop --command nixpkgs-fmt --check flake.nix

